title: "cheesecakecat"
description: Blog
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: "/blog/page/:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Theme settings
show_excerpts: true

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
